apiVersion: v1
kind: PersistentVolume
metadata:
  name: saleor-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: saleor-db-disk
    fsType: ext4
